version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: '08:00'
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: "@types/vscode"
    versions:
    - "> 1.55.0"